### PR TITLE
Various Updates Including Pi3 WiFi

### PR DESCRIPTION
**Pull request by johnisanerd**

### CODE REVIEW

**Comment by RobertLucian** [comment]
This PR seems to contain more than the changes we've merged with #165. The other changes are related to #161, #162. For some reason, `update` is not up-to-date with `master`. This PR will sync them.

**Comment by CleoQc** [comment]
btw, @RobertLucian 
What about all those lines similar to 
`sudo sh -c "curl -kL dexterindustries.com/update_sensors | bash"`  ?

Why call sh only to pipe into bash?

**Comment by RobertLucian** [comment]
@CleoQc we could have gone with `sudo bash -c "curl -kL dexterindustries.com/update_sensors | bash"` instead of `sh`, but at the moment, I can't remember why I chose `sh` instead of `bash`. 
Was your question about this?

**Comment by CleoQc** [comment]
why not just 
`sudo curl -kL dexterindustries.com/update_sensors | bash`

**Comment by johnisanerd** [comment]
So . . . merge.

**Comment by RobertLucian** [comment]
Oh, 'cause piping it to bash this way (the way you shown) will only make the script get executed without root privileges no matter what you prepend to your command. You either have got to login with the root user or launch it this way in order to inherit root's privileges.

**Pull request merged**
