### PR TITLE
Removal of build distributions-Final

### PR DESCRIPTION
**Pull request by Shoban94**

### CODE REVIEW

**Comment by CleoQc** [comment]
approved

**Comment by CleoQc** [comment]
actually not approved yet: 
use bash or sh after all?

**Comment by karan259** [comment]
@Shoban94 : what;s the change here . All I can see is a pushd and a popd command being removed. Was there another PR before this

**Comment by Shoban94** [comment]
Yeah Pushd and Popd wheren't helping me, so I have just used `rm` commands to remove those files.
So there will be only `rm` commands without the pushd and popd when compared to the previous PR.

**Comment by DexterInd** [comment]
@karan259 pointed out, this is really a modification of this:  https://github.com/DexterInd/Raspbian_For_Robots/pull/58  and @Shoban94 figured out that popd and pushd weren't effective.  Is that right @Shoban94 ?  Just cleaning up?

**Comment by Shoban94** [comment]
@karan259- Yes Karan exactly, pushd and popd weren't effective and I removed them, so that they don't affect any other part of the code

**Pull request merged**
