### PR TITLE
Bad command for Geany

### PR DESCRIPTION
**Pull request by CleoQc**
Remove a stray / when setting Geany as sudo
Not tested yet - I just don't want to lose track of it. Need to test it before merging. I'll do that tomorrow.

### CODE REVIEW

**Comment by CleoQc** [comment]
Symptom is that Geany does not start at all when requested from the top menu entry (the raspberry / programming / Geany)

**Comment by DexterInd** [comment]
Will wait for the test results before merging.

**Comment by CleoQc** [comment]
Tested and this needs to be in the image, otherwise geany will not be available .

**Comment by DexterInd** [comment]
@CleoQc Thanks! This is great work!

**Pull request merged**
