### PR TITLE
allow users to change the hostname using a file with a .txt extension

### PR DESCRIPTION
**Pull request by CleoQc**
It's easier to support a .txt extension than to train all users to remove the extension on their computer.

### CODE REVIEW

**Comment by DexterInd** [comment]
Thoughtful, and a really good point.

As a side note, that would make the start of a great haiku @CleoQc.

**Comment by DexterInd** [comment]
@Shoban94 and @CleoQc I was thinking about this the other day and forgot about it: what happens if a window user makes this new file `/boot/hostnames.txt` but it has a windows crlf in it?

**Comment by CleoQc** [comment]
most likely fine. If I remember correctly we are using regex to verify the validity of the string, which should take care of it

**Comment by DexterInd** [comment]
Wading out of my depth here, but is there a way to strip out the extra characters on a windows file?  Rejecting it is probably the first step, but I'm curious if there's a way we can heal it?

**Pull request merged**
