### PR TITLE
CINCH: make the SSID the same as the hostname

### PR DESCRIPTION
**Pull request by CleoQc**
I happened to have the code on hand. I went ahead and made the change. Feel free to accept or not.

### CODE REVIEW

**Comment by CleoQc** [comment]
It takes up to three reboots for the name change to be reflected within Cinch. I'll take a closer look tomorrow. I can save at least one reboot in one case, but I'm looking for a better solution.

**Comment by DexterInd** [comment]
Is the reboot issue just on Jessie?  Or is it on wheezy as well?

**Comment by CleoQc** [comment]
Cinch only works for Wheezy for now

**Comment by DexterInd** [comment]
@CleoQc Thank you!!

**Pull request merged**
