### PR TITLE
Pi3 Wifi Working - Hotfix

### PR DESCRIPTION
**Pull request by johnisanerd**
Turning this PR into a hotfix on the main branch.  

This should make Cinch work with the Pi3 Wifi and the Wifi Dongle.

I have tested this back and forth a few times, works with both the dongle and the Pi3 onboard WiFi.
[
The image is up here for testing. ](https://sourceforge.net/projects/dexterindustriesraspbianflavor/files/Cinch/)

### CODE REVIEW

**Comment by johnisanerd** [comment]
@RobertLucian this one is waiting on you; everything ok?

**Comment by RobertLucian** [comment]
I haven't see this one - thanks for tagging me in here. I'll be back with a review.

**Comment by johnisanerd** [comment]
I will merge; but @RobertLucian just a point of order here:  do I also make a PR into the "develop" branch as well?  Same PR?

**Comment by RobertLucian** [comment]
No, it's fine if you just merge the `master` into `develop` and then push. It's the `master` we're after to protect.

**Comment by johnisanerd** [comment]
Good to know for next time.  I took a different route, but hopefully it worked out?

**Pull request merged**
