### PR TITLE
working cinch setup script for jessie

### PR DESCRIPTION
**Pull request by dlech**
* Using dnsmasq instead of isc-dhcp-server
* Use conf.d directories when possible instead of replacing main conf files.
* Backup main conf files that must be replaced
* Get rid of all the sudos - script must be run as root.
* Make script executable
* Use SCRIPTDIR variable so script can be run from any location
* rc.local script is no longer needed

### CODE REVIEW

**Comment by DexterInd** [comment]
We ran this on a Pi2 today succesfully, need to test it on a Pi3.  Might have an issue with the wlan0 and wlan1 there.

**Comment by dlech** [comment]
Shouldn't be too hard to fix. Would you be using the built-in WiFi on Pi3 or the Dexter Industries dongle?

**Comment by DexterInd** [comment]
@dlech and @CleoQc , I had success by adding the following:

The only other thing I can think of is to disable the loading of the drivers for now in the file `/etc/modprobe.d/raspi-blacklist.conf` :
```

blacklist brcmfmac
blacklist brcmutil

```

**Comment by DexterInd** [comment]
@CleoQc can you give this a shot to confirm?

**Comment by dlech** [comment]
@DexterInd, is your previous comment missing something between these two sentences?

> I had success by adding the following:
>
> Is there supposed to be more here?

**Comment by DexterInd** [comment]
@dlech my original comment, with formatting removed:

I had success on the Pi 3 by adding the following:

Disable the loading of the drivers for now in the file /etc/modprobe.d/raspi-blacklist.conf, adding this:
blacklist brcmfmac
blacklist brcmutil

**Comment by dlech** [comment]
OK. I couldn't tell if you were proposing one idea or two different ideas.

I think this is a good idea if you are using the DI WiFi dongle with RPi3. Not only does it get cinch working, it will also reduce the confusion of having multiple `wlanX` network devices.

Suggestion: instead of adding to `/etc/modprobe.d/raspi-blacklist.conf`, create a new file `/etc/modprobe.d/cinch-blacklist.conf`. I will have the same effect and will be obvious where it came from.

**Comment by CleoQc** [comment]
it looks like my Pi3 has decided to start working, using the onboard wlan0.
Let me do everything from scratch again, and double make sure I'm not hallucinating. If it's true, it would be fantastic.

**Comment by DexterInd** [comment]
Tested it one more time on @dlech 's branch and everything worked with the latest Jessie.  I'm going to merge this now, thanks @CleoQc .

**Pull request merged**
